services:
  db:
    image: ${REGISTRY:-docker.wacmk.icu/wacmk-dragon-nest}/${MYSQL_IMAGE:-mariadb}
    container_name: wacmk-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-123456}
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - "${MYSQL_DATA:-./db}:/var/lib/mysql"
    networks:
      - wacmk-network
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--connect",
          "--mariadbupgrade",
          "--innodb_initialized",
        ]
      interval: 20s
      start_period: 30s
      timeout: 5s
      retries: 10

  redis:
    image: ${REGISTRY:-docker.wacmk.icu/wacmk-dragon-nest}/${REDIS_IMAGE:-redis}
    container_name: wacmk-redis
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:-iguozicc}"
    networks:
      - wacmk-network

  dn-server:
    image: ${REGISTRY:-docker.wacmk.icu/wacmk-dragon-nest}/wacmk-dn-${SERVER_TYPE:-fwl}:${SERVER_VERSION:-latest}
    container_name: wacmk-dn-server
    volumes:
      - ${SERVER_DATA:-./server}:/data
      - ${SERVER_LOG:-./logs}:/logs
    environment:
      - INIT_MODE=${INIT_MODE:-false}
      - UPDATE_MODE=${UPDATE_MODE:-false}
      - MYSQL_HOST=${MYSQL_HOST:-db}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-123456}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_DB_LOGIN=${MYSQL_DB_LOGIN:-login}
      - MYSQL_DB_WORLD=${MYSQL_DB_WORLD:-world}
      - MYSQL_DB_GLOBALWORLD=${MYSQL_DB_GLOBALWORLD:-globalworld}
      - MYSQL_DB_DRAGON_NEST_ONLINE=${MYSQL_DB_DRAGON_NEST_ONLINE:-db_Dragon_Nest_online}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-iguozicc}
      - SERVER_IP=${SERVER_IP:?请在 .env 中设置 SERVER_IP 后再启动服务}
      - SERVER_PORT=${SERVER_PORT:-10201}
      - SERVER_NAME=${SERVER_NAME:-WACMKDragonNest}
      - SERVER_REGION_NAME=${SERVER_REGION_NAME:-WACMKDragonNest}
      - SERVER_OPEN_TIME=${SERVER_OPEN_TIME:-2020-04-01 16:00:00}
      - SERVER_FULL_REGISTER_TIME=${SERVER_FULL_REGISTER_TIME:-2020-04-01 16:10:00}
      - ID_IP_LINK_PORT=${ID_IP_LINK_PORT:-58003}
    ports:
      - ${SERVER_PORT:-10201}:${SERVER_PORT:-10201}
      - ${ID_IP_LINK_PORT:-58003}:${ID_IP_LINK_PORT:-58003}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wacmk-network

  dn-web:
    image: ${REGISTRY:-docker.wacmk.icu/wacmk-dragon-nest}/wacmk-dn-${SERVER_TYPE:-fwl}-web:${SERVER_VERSION:-latest}
    container_name: wacmk-dn-web
    volumes:
      - ${WEB_DATA:-./www}:/var/www
    ports:
      - ${WEB_PORT:-80}:80
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wacmk-network

networks:
  wacmk-network:
    name: wacmk-network
